### ISSUE TITLE
Failed to connect to server. Reason: java.net.SocketException: Broken pipe (Write failed).

### ISSUE THREAD

**Issue by szsuyuji** [brenoae/metabase-impala-driver#4]
need check connection

**Comment by brenoae** [comment]
Hello @szsuyuji , I'm facing the same problem and I coudn't identify the cause yet.
Have you solved this problem?

**Comment by szsuyuji** [comment]
@brenoae my problem was because of the load balance proxy . use direct connection with one server it works well. i guess it can be fixed if check the connection before use.

**Comment by studB** [comment]
If problem was the load balance proxy, the cause would be that the tcp connection between the metabase and proxy was transformed to the CLOSE-WAIT. Probably changed like that when metabase didn't send any queries for 'server timeout time'. You should change a timeout option.
